version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      # QUYIDAGI QATORNI QO'SHING: Pip keshini saqlash uchun
      - pip_cache:/root/.cache/pip
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    # QUYIDAGI QATORNI QO'SHING: Pipga kesh papkasini ko'rsatish
    environment:
      - PIP_CACHE_DIR=/root/.cache/pip

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ecom_db
      - POSTGRES_USER=ecom_user
      - POSTGRES_PASSWORD=samandar@1975

  redis:
    image: redis:7-alpine

  # Yangi Celery ishchisi
  celery:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-change-me-later
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
      - db
      - web  

volumes:
  postgres_data:
  # QUYIDAGI QATORNI QO'SHING: Volume yaratish
  pip_cache: